In [1]:
import pandas as pd

In [2]:
base = pd.read_csv('IMDB Dataset.csv')
base

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
base["label"] = base.sentiment.map({"positive": 1, "negative": 0})
base.label.value_counts()

label
1    25000
0    25000
Name: count, dtype: int64

In [4]:
split = ["valid" for _ in range(1000)] + ["test" for _ in range(5000)] + ["train" for _ in range(len(base) - 6000)]

base = base.sample(frac=1.0, replace=False, random_state=1)
base["split"] = split
base.split.value_counts()

split
train    44000
test      5000
valid     1000
Name: count, dtype: int64

In [5]:
base = base.rename(columns={"review": "texto"})

In [8]:
from tokenizer import BPETokenizer, SPECIAL_TOKENS

tokenizer = BPETokenizer(vocab_size=5_000, merges_path="C:/Users/luisc/local/projetos/videos/transformer_/artifacts/tokenizer_wiki_en_5k.json")
tokenized = tokenizer.batch_encode(base.texto.tolist())

Tokenizando em paralelo: 100%|██████████| 50000/50000 [05:21<00:00, 155.47doc/s]

In [11]:
print(tokenizer.decode(tokenized[0]))

With No Dead Heroes you get stupid lines like that as this woefully abysmal action flick needs to be seen to be believed. William Sanders is saved by his buddy Harry Cotter during an extraction in Vietnam but gets himself captured by the enemy. Fast forward ten years and Harry is now a brainwashed Russian operative with a mind control microchip implanted in his brain. His new Russian superior is Ivan played to the obscene hilt by Nick Nicholson who might I add not only doesn't attempt once to speak with a Russian accent but resembles more a gas station attendant in Kentucky with his stained teeth. What is even more absurd is the fact that he was also the dialog coach for this film. Soon William is re-recruited by the CIA to hunt Harry down. He teams up with Barbara, a freedom fighter who has infiltrated Ivan's El Salvador camp and soon the both of them are blowing up half of South America. Some scenes are so jaw droppingly awful that it's a wonder why this film doesn't have more of a cult following. One such scene is the sudden lovemaking in the jungle by William and Barbara accompanied by the most inappropriate catterwalling background music I've ever heard. Who would strip completely nude in the middle of a South American jungle? There is a rape scene that uses the end theme from Blood on Satan's Claw as well. No Dead Heroes is the magic bullet movie champion of all time as one shot leads to multiple kills. In one scene Harry strafes his rifle from behind a rock and kills seven guys. I had to rewind it and count. Hard to find film that has recently gotten the full HD treatment by MGM. Track this movie down and watch it for the sheer silliness that ensues.

In [12]:
base["tokens"] = tokenized

In [13]:
base.to_parquet("base_imdb.pq")

In [14]:
base

,texto,sentiment,label,split,tokens
26247,With No Dead Heroes you get stupid lines like ...,negative,0,valid,"[2260, 3985, 911, 551, 1422, 115, 302, 3303, 2..."
35067,I thought maybe... maybe this could be good. A...,negative,0,valid,"[739, 4265, 4020, 392, 50, 50, 50, 36, 4020, 5..."
34590,An elite American military team which of cours...,negative,0,valid,"[2413, 297, 718, 585, 2234, 1149, 469, 278, 42..."
16668,Ridiculous horror film about a wealthy man (Jo...,negative,0,valid,"[86, 433, 4079, 634, 2062, 118, 310, 1015, 869..."
12196,"Well, if you are one of those Katana's film-nu...",positive,1,valid,"[4951, 48, 36, 1815, 3303, 444, 494, 278, 1800..."
...,...,...,...,...,...
43723,The larger-than-life figures of Wyatt Earp and...,positive,1,train,"[325, 1619, 265, 49, 262, 266, 49, 1582, 2613,..."
32511,"Okay, you have:<br /><br />Penelope Keith as M...",negative,0,train,"[3683, 359, 48, 36, 3303, 373, 884, 62, 64, 53..."
5192,"An odd, willfully skewed biopic of Dyan Thomas...",negative,0,train,"[2413, 422, 104, 48, 36, 123, 492, 3113, 918, ..."
12172,"Basic structure of a story: Beginning, Middle,...",negative,0,train,"[1778, 398, 3551, 278, 281, 4871, 62, 36, 969,..."
33003,"Set in Paris in the year 1910, a retired old r...",positive,1,train,"[87, 530, 283, 4693, 283, 269, 1195, 53, 61, 5..."

In [15]:
base["num_tokens"] = base.tokens.apply(len)
base.num_tokens.describe()

count    50000.000000
mean       449.719340
std        340.071117
min         12.000000
25%        238.000000
50%        333.000000
75%        547.000000
max       4681.000000
Name: num_tokens, dtype: float64

In [16]:
base.info()

<class 'pandas.DataFrame'>
Index: 50000 entries, 26247 to 33003
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   texto       50000 non-null  str
 1   sentiment   50000 non-null  str
 2   label       50000 non-null  int64
 3   split       50000 non-null  str
 4   tokens      50000 non-null  object
 5   num_tokens  50000 non-null  int64
dtypes: int64(2), object(1), str(3)
memory usage: 65.7+ MB

In [17]:
type(base.tokens.values[0])

list